version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data: